import type { Metadata } from "next";import "./globals.css";
import { Red_Hat_Display } from "next/font/google";
import clsx from "clsx";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ['400', '500','600','700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-red-hat-display'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
    >
      <body className={clsx(redHatDisplay.variable, 'antialiased')}>{children}</body>
    </html>
  );
}
